---
- name: install dependencies - nodeJs & npm
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: present


- name: node version
  become: true
  npm:
    name: nodejs
    global: yes
    version: 'v13.8.0'


- name: install pm2
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
