---
- name: install dependencies - nodeJs & npm
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest

- name: install pm2
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: create backend directory
  file:
    path: ~/backend_app
    state: directory

- name: copy artifact into instance
  copy:
    src: ~/project/artifact.tar.gz
    dest: ~/backend_app/artifact.tar.gz

- name: extract backend
  shell: |
    cd ~/backend_app
    tar xzvf artifact.tar.gz
    ls -l
  register: extract_output

- debug:
    var: extract_output.stdout_lines


- name: start app
  become: true
  shell: |
    cd ~/backend_app
    npm install
    npm run build
    pm2 stop all
    pm2 start npm -- start
  register: command_output

- debug:
    var: command_output.stdout_lines
