---
- name: install dependencies - nodeJs & npm
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest

- name: install pm2
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: create backend directory
  file:
    path: ~/backend_app
    state: directory

- name: copy artifact into instance
  copy:
    src: ~/project/artifact.tar.gz
    dest: ~/backend_app/artifact.tar.gz

- name: extract_backend
  become: true
  become_method: sudo
  shell: |
    cd ~/
    apt-get install tar -y
    ls -a
    cd backend_app
    tar -xzvf artifact.tar.gz
    ls -a
  register: extract_output

- debug:
    var: extract_output.stdout_lines

- name: start-up
  become: true
  shell:  |
    cd ~/
    cd babackend_app
    npm install
    npm run build
    pm2 stop default
    pm2 start npm -- start
  register: start_up
- debug:
    var:  start_upstdout_lines
