---
- name: install dependencies - nodeJs & npm
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest

- name: install pm2
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: create backend directory
  file:
    path: ~/backend_app
    state: directory

- name: copy artifact into instance
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend_app/

# - name: extract_backend
#   shell: |
#     cd ~/backend_app
#     tar -xzvf artifact.tar.gz
#     ls -a
#   register: extract_output
# - debug:
#     var: extract_output.stdout_lines

- name: build
  shell: |
    cd ~/backend_app
    npm install
    npm run build
  register: start_up
- debug:
    var: start_up.stdout_lines

- name: start
  shell: |
    cd ~/backend_app/dist
    pm2 stop default
    pm2 start main.js
  
  register: execute_node
- debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: Start service on startup
  shell: |
    sudo su -c "env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"
    pm2 save