---
- name: install dependencies - nodeJs & npm
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
    sudo apt-get install -y nodejs
    sudo npm install -g n
    sudo n 13.8.0

- name: install pm2
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: create backend directory
  file:
    path: ~/backend_app
    state: directory

- name: copy artifact into instance
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/backend_app

- name: build app
  become: true
  shell: |
    cd /home/ubuntu/backend_app
    npm install
    # npm run build

- name: start app
  become: true
  shell: |
    cd /home/ubuntu/backend_app/
    pm2 stop default
    sleep 20
    pm2 start npm -- start

- name: Start service on startup
  shell: |
    sudo su -c "env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"
    pm2 save